// This code is generated by AwesomeParserGenerator2000 (by @lexzhe)

package calculator;

import java.util.*;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

public class Lexer {

    private String data;

    private final Map<Pattern, Terminal> map;

    public Lexer(String data) {
        this.data = data.replaceAll("[ \n\t]", "");
        map = new LinkedHashMap<>();
        map.put(Pattern.compile("(A).*"), Terminal.A);
        map.put(Pattern.compile("(A).*"), Terminal.B);
        map.put(Pattern.compile("([0-9]+(\\.[0-9]+)?).*"), Terminal.NUMBER);
        map.put(Pattern.compile("(\\+).*"), Terminal.PLUS);
        map.put(Pattern.compile("(\\*\\*).*"), Terminal.STARS);
        map.put(Pattern.compile("(\\*).*"), Terminal.MULT);
        map.put(Pattern.compile("(//).*"), Terminal.LOG);
        map.put(Pattern.compile("(/).*"), Terminal.DIV);
        map.put(Pattern.compile("(-).*"), Terminal.MINUS);
        map.put(Pattern.compile("(\\().*"), Terminal.LP);
        map.put(Pattern.compile("(\\)).*"), Terminal.RP);

    }

    public List<Token> parseAll() {
        List<Token> tokens = new ArrayList<>();
        while (true) {
            Token current = getToken();
            tokens.add(current);
            if (current.terminal == Terminal.END) {
                return tokens;
            }
        }
    }

    private Token getToken() {
        if (data.isEmpty()) {
            return new Token(Terminal.END);
        }

        for (Map.Entry<Pattern, Terminal> entry : map.entrySet()) {
            Pattern pat = entry.getKey();
            Terminal terminal = entry.getValue();
            Matcher matcher = pat.matcher(data);
            if (matcher.matches() && !matcher.group().isEmpty()) {
                String result = matcher.group(1);
                int len = result.length();
                if (len < data.length()) {
                    data = data.substring(len);
                } else {
                    data = "";
                }
                return new Token(terminal, result);
            }

        }

        return new Token(Terminal.END);
    }

}

