// This code is generated by AwesomeParserGenerator2000 (by @lexzhe)

package calculator;

public class Token {

    public Terminal terminal;

    public String text = "";

    public Token(Terminal terminal, String text) {
        this.terminal = terminal;
        this.text = text;
    }

    public Token(Terminal terminal) {
        this.terminal = terminal;
    }

    @Override
    public String toString() {
        return terminal.name() + " : \"" + text + "\" ";
    }
}



